// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.Unhumandomains
{
    [EnumType]
    public readonly struct DnsRecordType : IEquatable<DnsRecordType>
    {
        private readonly string _value;

        private DnsRecordType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static DnsRecordType A { get; } = new DnsRecordType("A");
        public static DnsRecordType AAAA { get; } = new DnsRecordType("AAAA");
        public static DnsRecordType CNAME { get; } = new DnsRecordType("CNAME");
        public static DnsRecordType TXT { get; } = new DnsRecordType("TXT");
        public static DnsRecordType MX { get; } = new DnsRecordType("MX");

        public static bool operator ==(DnsRecordType left, DnsRecordType right) => left.Equals(right);
        public static bool operator !=(DnsRecordType left, DnsRecordType right) => !left.Equals(right);

        public static explicit operator string(DnsRecordType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DnsRecordType other && Equals(other);
        public bool Equals(DnsRecordType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
