// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unhumandomains.Outputs
{

    [OutputType]
    public sealed class DnsRecord
    {
        public readonly string? Ip;
        public readonly double? Priority;
        public readonly string Subdomain;
        public readonly string? Target;
        public readonly Pulumi.Unhumandomains.DnsRecordType Type;
        public readonly string? Value;

        [OutputConstructor]
        private DnsRecord(
            string? ip,

            double? priority,

            string subdomain,

            string? target,

            Pulumi.Unhumandomains.DnsRecordType type,

            string? value)
        {
            Ip = ip;
            Priority = priority;
            Subdomain = subdomain;
            Target = target;
            Type = type;
            Value = value;
        }
    }
}
