// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unhumandomains.Inputs
{

    public sealed class DnsRecordArgs : global::Pulumi.ResourceArgs
    {
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("priority")]
        public Input<double>? Priority { get; set; }

        [Input("subdomain", required: true)]
        public Input<string> Subdomain { get; set; } = null!;

        [Input("target")]
        public Input<string>? Target { get; set; }

        [Input("type", required: true)]
        public Input<Pulumi.Unhumandomains.DnsRecordType> Type { get; set; } = null!;

        [Input("value")]
        public Input<string>? Value { get; set; }

        public DnsRecordArgs()
        {
        }
        public static new DnsRecordArgs Empty => new DnsRecordArgs();
    }
}
